"""add fields to companies

Revision ID: 73701be4e704
Revises: d218f42b5f6d
Create Date: 2025-10-25 01:24:28.342586

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73701be4e704'
down_revision: Union[str, Sequence[str], None] = 'd218f42b5f6d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('workers', sa.Integer(), nullable=False))
    op.add_column('companies', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.alter_column('companies', 'name',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('companies', 'activity',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)
    op.alter_column('companies', 'risk_level',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=32),
               existing_nullable=False)
    op.drop_constraint(op.f('companies_ruc_key'), 'companies', type_='unique')
    op.create_index(op.f('ix_companies_owner_id'), 'companies', ['owner_id'], unique=False)
    op.create_index(op.f('ix_companies_ruc'), 'companies', ['ruc'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_companies_ruc'), table_name='companies')
    op.drop_index(op.f('ix_companies_owner_id'), table_name='companies')
    op.create_unique_constraint(op.f('companies_ruc_key'), 'companies', ['ruc'], postgresql_nulls_not_distinct=False)
    op.alter_column('companies', 'risk_level',
               existing_type=sa.String(length=32),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('companies', 'activity',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)
    op.alter_column('companies', 'name',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)
    op.drop_column('companies', 'updated_at')
    op.drop_column('companies', 'workers')
    # ### end Alembic commands ###
